apiDir: "../headless-commerce-admin-account-api/src/main/java"
apiPackagePath: "com.liferay.headless.commerce.admin.account"
application:
    baseURI: "/headless-commerce-admin-account"
    className: "HeadlessCommerceAdminAccountApplication"
    name: "Liferay.Headless.Commerce.Admin.Account"
author: "Alessio Antonio Rendina"